name: CI on PR to weekly-branch

on:
  pull_request:
    branches: [ "weekly/*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Set up properties
      - name: Set up properties
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties
          cat application.properties

      # Build and Test
      - name: Test with Gradle Wrapper
        id: gradle-test
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      # Show test result
      - name: Show test result
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Add check comments for failed code lines on test failure
      - name: Add comments for failed code lines
        uses: mikepenz/action-junit-report@v3
        if: failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}